# Site wide configuration

title: TIGRlab
description: "The Kimel Family Translational Imaging Genetics Research Laboratory"
logo: 120x120.gif
teaser: projects.dti-aging.small.jpg
locale: en_CA
url: //tigrlab.github.io
# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
markdown: kramdown
highlighter: rouge
gems:
  - jekyll-sitemap
  - jekyll-redirect-from

# Site owner
owner:
  name: Joseph D Viviano
  web: http://viviano.ca
  email: joseph@viviano.ca


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
